version: '3.8'

services:
  # Main workstation - where you'll develop and run your ML code
  workstation:
    image: ubuntu:24.04
    container_name: workstation
    hostname: workstation.lab
    networks:
      - lab_network
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./training_data:/data/training_data
      - activity_logs:/var/log/activity:ro
    working_dir: /data
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      bash -c "
        echo 'Installing dependencies...' &&
        apt-get update -qq &&
        apt-get install -y -qq python3 git curl wget vim net-tools iputils-ping &&
        mkdir -p /data/output/{models,logs,alerts,retraining_logs} /data/accumulated_data &&
        chmod -R 755 /data/output /data/accumulated_data &&
        touch /tmp/workstation_ready &&
        echo '=== Workstation ready ===' &&
        echo 'Starting background services...' &&
        echo '- Data Accumulator (2 min snapshots)' &&
        echo '- Retraining Scheduler (2 min intervals)' &&
        (python3 /scripts/data_accumulator.py --interval 120 > /data/output/accumulator.log 2>&1 & \
        python3 /scripts/retraining_scheduler.py --interval 120 --min-samples 30 > /data/output/retraining.log 2>&1 & \
        wait)
      "
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/workstation_ready && python3 --version || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 24
      start_period: 120s
    depends_on:
      - target
      - monitor

  # Target system - generates normal user activity
  target:
    image: ubuntu:24.04
    container_name: target
    hostname: target.lab
    networks:
      - lab_network
    volumes:
      - activity_logs:/var/log/activity
      - ./scripts:/scripts
      - ./data/poisoning:/data/poisoning
      - ./data/output/retraining_logs:/data/output/retraining_logs:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y -qq python3 python3-pip net-tools &&
        pip3 install --break-system-packages faker &&
        echo '=== Target system ready ===' &&
        python3 /scripts/generate_activity.py &
        tail -f /dev/null
      "

  # Monitor - collects and processes activity logs  
  monitor:
    image: ubuntu:24.04
    container_name: monitor
    hostname: monitor.lab
    networks:
      - lab_network
    volumes:
      - activity_logs:/var/log/activity:ro
      - ./data:/data
      - ./scripts:/scripts
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y -qq python3 net-tools &&
        echo '=== Monitor ready ===' &&
        sleep 10 &&
        python3 /scripts/process_logs.py &
        tail -f /dev/null
      "

volumes:
  activity_logs:

networks:
  lab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
