#!/bin/bash
# Quick reference for running system tests

echo "======================================================================"
echo "System Tests Quick Reference"
echo "======================================================================"
echo ""
echo "PREREQUISITES:"
echo "  1. Docker and docker-compose installed and running"
echo "  2. Python dependencies installed (pytest, docker, pytest-timeout)"
echo ""
echo "INSTALL DEPENDENCIES:"
echo "  pip install pytest==7.4.3 pytest-timeout==2.2.0 docker==7.0.0"
echo ""
echo "======================================================================"
echo "RUN COMMANDS"
echo "======================================================================"
echo ""
echo "1. Run ALL system tests (~35 minutes):"
echo "   pytest tests/system/ -v -s --timeout=1800"
echo ""
echo "2. Run SPECIFIC test file:"
echo "   pytest tests/system/test_container_integration.py -v -s"
echo "   pytest tests/system/test_end_to_end_detection.py -v -s"
echo "   pytest tests/system/test_retraining_cycle.py -v -s"
echo "   pytest tests/system/test_poisoning_impact.py -v -s"
echo ""
echo "3. Run SPECIFIC test:"
echo "   pytest tests/system/test_end_to_end_detection.py::TestEndToEndDetection::test_01_initial_training_creates_model -v -s"
echo ""
echo "======================================================================"
echo "TEST FILES"
echo "======================================================================"
echo ""
echo "test_container_integration.py  - 8 tests,  ~5 min  - Docker orchestration"
echo "test_end_to_end_detection.py   - 8 tests,  ~5 min  - Detection pipeline"
echo "test_retraining_cycle.py       - 7 tests, ~10 min  - Retraining cycles"
echo "test_poisoning_impact.py       - 6 tests, ~15 min  - Poisoning attacks"
echo ""
echo "TOTAL: 29 tests, ~35 minutes"
echo ""
echo "======================================================================"
echo "DEBUGGING"
echo "======================================================================"
echo ""
echo "View container logs:"
echo "  docker logs workstation"
echo "  docker logs target"
echo "  docker logs monitor"
echo ""
echo "Check container status:"
echo "  docker ps"
echo ""
echo "Access container shell:"
echo "  docker exec -it workstation bash"
echo ""
echo "Clean up after failed tests:"
echo "  docker-compose down -v"
echo ""
echo "======================================================================"
